[package]
name = "opencv"
version = "0.0.1"
authors = [ "woxtu <woxtup@gmail.com>" ]
description = "Wrapper for OpenCV"
license = "MIT"

[features]
default = ["opencv24"]
opencv24 = []
opencv30 = []

[lib]
name = "opencv"
path = "src/lib.rs"

[dependencies]
enum_primitive = "*"
num = "*"
libc = "*"
